places = [
    { nhs = [1, 2], vp = 3, qty = 3, field_type = "Wood", enemy = "Sweden" },
    { nhs = [0, 2, 5], vp = 4, qty = 3, field_type = "Food", enemy = "Sweden" },
    { nhs = [0, 1, 5, 6, 3], vp = 2, qty = 2, field_type = "Wood", enemy = "Sweden" },
    { nhs = [2, 6, 4], vp = 2, qty = 2, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [3, 10], vp = 3, qty = 2, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [1, 2, 6, 8, 7], vp = 3, qty = 1, field_type = "Food", enemy = "Sweden" },
    { nhs = [2, 5, 8, 9, 3], vp = 2, qty = 3, field_type = "Wood", enemy = "Sweden" },
    { nhs = [5, 8, 11, 13], vp = 2, qty = 3, field_type = "Food", enemy = "Sweden" },
    { nhs = [5, 7, 11, 9, 6], vp = 2, qty = 3, field_type = "Wood", enemy = "Sweden" },
    { nhs = [6, 8, 12], vp = 2, qty = 2, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [4, 12, 15, 16], vp = 3, qty = 3, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [7, 8, 13, 14], vp = 2, qty = 2, field_type = "Food", enemy = "Sweden" },
    { nhs = [9, 10, 15], vp = 2, qty = 2, field_type = "Food", enemy = "Vladimir" },
    { nhs = [7, 11, 14], vp = 4, qty = 2, field_type = "Wood", enemy = "Sweden" },
    { nhs = [11, 13, 17, 18], vp = 2, qty = 1, field_type = "Food", enemy = "Sweden" },
    { nhs = [12, 10, 16, 19, 18], vp = 2, qty = 1, field_type = "Food", enemy = "Vladimir" },
    { nhs = [20, 19, 15, 10], vp = 2, qty = 2, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [14, 18, 23, 22], vp = 3, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [14, 17, 23, 15, 19], vp = 2, qty = 1, start = 6, field_type = "Food", enemy = "Sweden" },
    { nhs = [15, 16, 20, 24, 18], vp = 2, qty = 1, start = 1, field_type = "Food", enemy = "Vladimir" },
    { nhs = [19, 16, 24, 27, 28, 21], vp = 2, qty = 2, field_type = "Wood", enemy = "Vladimir" },
    { nhs = [20, 28], vp = 4, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [17, 23, 25, 30, 29], vp = 4, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [17, 18, 25, 22], vp = 2, qty = 1, start = 5, field_type = "Food", enemy = "Polock" },
    { nhs = [19, 20, 27, 26], vp = 2, qty = 1, start = 2, field_type = "Food", enemy = "Polock" },
    { nhs = [23, 22, 30, 31, 26], vp = 2, qty = 1, start = 4, field_type = "Food", enemy = "Polock" },
    { nhs = [25, 31, 27, 24], vp = 2, qty = 1, start = 3, field_type = "Food", enemy = "Polock" },
    { nhs = [24, 26, 33, 28, 20], vp = 2, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [21, 20, 27, 33], vp = 4, qty = 3, field_type = "Food", enemy = "Vladimir" },
    { nhs = [22, 30, 32], vp = 3, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [22, 25, 31, 32, 29], vp = 2, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [32, 30, 25, 26], vp = 2, qty = 1, field_type = "Food", enemy = "Polock" },
    { nhs = [29, 30, 31], vp = 4, qty = 2, field_type = "Wood", enemy = "Polock" },
    { nhs = [28, 29], vp = 2, qty = 2, field_type = "Food", enemy = "Polock" },
]
