wood = 20
food = 20
metal = 20
weapon = 20
wax = 20
wool = 20
money = 600
people = 120
weapons = 10
feeds = 10
waxes = 10
wools = 10
church = 10
school = 10
action_cards = []
law_cards = []
war_cards_infantry = []
war_cards_cavalry = []
war_cards_archer = []
