weapons = 0.0
feeds = 0.0
waxes = 0.0
wools = 0.0
church = 0.0
school = 0.0
archbishop = 5.0
mayor = 5.0
commander = 5.0
wood_field = 0.0
eat_field = 0.0
wood = 0.5
food = 0.5
metal = 0.5
weapon = 1.0
wax = 1.0
wool = 2.0
money = 0.4
people = 0.0
vp = 1.0
reputation = 0.0
action_cards = 0.0
law_cards = 0.0
war_cards_infantry = 2.0
war_cards_cavalry = 2.0
war_cards_archer = 2.0
